# Generated by Django 5.2.11 on 2026-03-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_name',
            new_name='seller',
        ),
    ]
