# Generated by Django 5.2.11 on 2026-02-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product'),
        ('seller', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seller.subcategory'),
            preserve_default=False,
        ),
    ]
