# Generated by Django 5.2.11 on 2026-03-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_phone'),
        ('core', '0005_product_approved'),
    ]

    operations = [
    ]
