# Generated by Django 5.2.11 on 2026-02-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='AddProduct',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
