# Generated by Django 5.2.11 on 2026-03-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_subcategory_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.DeleteModel(
            name='AttributeValues',
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
