# Generated by Django 5.2.11 on 2026-03-31 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_remove_productvarient_attribute_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.FileField(max_length=50, upload_to='verification_docs/')),
                ('note', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile')),
            ],
        ),
    ]
